name: working dirs & shells
on: [push]
jobs:
  display-wd-info:
    runs-on: windows-latest
    steps:
      - name: Display working directory & shells
        run: |
          cwd
          dir
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
  display-wd-info-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Display working directory & shells
        run: |
          cwd
          dir
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY  
